#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIDI-Morph
version:      0.01
version_from: lib/MIDI/Morph.pm
installdirs:  site
requires:
    MIDI:                          0.8
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
