#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIDI-Morph
version:      0.02
version_from: lib/MIDI/Morph.pm
installdirs:  site
requires:
    Test::More:                    0
    MIDI:                          0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
